color0 #53443a
color1 #ffb4ab
color2 #ffb786
color3 #eabda1
color4 #cacc70
color5 #ffb786
color6 #eabda1
color7 #eee0d9
color8 #a08d82
color9 #ffb4ab
color10 #ffb786
color11 #eabda1
color12 #cacc70
color13 #ffb786
color14 #eabda1
color15 #eee0d9

cursor                #eee0d9
cursor_text_color     #18120e
background            #18120e
foreground            #eee0d9
selection_foreground  #d8c2b6
selection_background  #53443a
active_border_color   #ffb786
inactive_border_color #53443a
url_color             #ffb786

active_tab_foreground   #502400
active_tab_background   #ffb786
inactive_tab_foreground #d8c2b6
inactive_tab_background #53443a
cursor_trail_color      #d8c2b6
